/* AUTO-GENERATED by build.js from tome-src/10_engine.js — do not hand-edit, do not hand-copy. */
/* ---------- engine 2.0 ---------- */
let OVERRIDES = {};
const E2 = (() => {
  let DICT = null, COMMON = new Map(), INDEX = null, status = "idle", error = "";
  const CURATED = new Set(LEXICON);
  let OWN = new Set();                       // the tier you write in: bank + every shelved draft
  function setOwn(words) { OWN = new Set(words.map(clean).filter(w => w.length > 1)); POOL = null; }
  const RED = new Set(["AH","IH","EH","AE","AA","UH"]);
  const clean = raw => raw.toLowerCase().replace(/[^a-z']/g, "");
  function parseCompact(str) {
    const [vs, coda] = str.split("|")[0].split("-");
    const sylls = vs.split(".").map(t => ({ v: t.replace(/\d/, ""), s: +t.slice(-1), c: "" }));
    sylls[sylls.length-1].c = coda || "";
    sylls.forEach(s => { s.reduced = s.v === "AH" && s.s === 0; });
    return sylls;
  }
  function parseOne(str) {
    const [vs, coda] = str.split("-");
    const sylls = vs.split(".").map(t => ({ v: t.replace(/\d/, ""), s: +t.slice(-1), c: "" }));
    sylls[sylls.length-1].c = coda || "";
    sylls.forEach(s => { s.reduced = s.v === "AH" && s.s === 0; });
    return sylls;
  }
  /* every read the dictionary carries for a word, primary first; [] if unknown */
  function variants(raw) {
    const w = clean(raw);
    if (!DICT || !Object.hasOwn(DICT, w)) return [];
    return DICT[w].split("|").map(parseOne);
  }
  function pronounce(raw) {
    const w = clean(raw);
    if (!w) return { sylls: [], source: "none" };
    const ov = Object.hasOwn(OVERRIDES, w) ? OVERRIDES[w] : null;
    const caps = raw.replace(/[^A-Za-z]/g, "");
    const initialism = caps && caps === caps.toUpperCase() && caps.length <= 4 &&
      (!/[AEIOU]/.test(caps) || !(DICT && Object.hasOwn(DICT, w)));
    let sylls, source;
    if (initialism) {
      sylls = caps.toLowerCase().split("").map(ch => { const [v, c] = LETTERS[ch] || ["AH",""]; return { v, c, s: 1 }; });
      source = "initialism";
    } else if (Object.hasOwn(EXCEPTIONS, w)) {
      /* a trailing digit on the vowel carries CMUdict-style stress (AH0, EY2); no digit means primary, so untagged entries keep their old reading */
      sylls = EXCEPTIONS[w].map(t => {
        const [raw, c] = t.split("-"), tagged = /\d$/.test(raw);
        return { v: tagged ? raw.slice(0, -1) : raw, c: c || "", s: tagged ? +raw.slice(-1) : 1 };
      });
      source = "exception";
    } else if (DICT && Object.hasOwn(DICT, w)) { sylls = parseCompact(DICT[w]); source = "cmu"; }
    else { sylls = g2p(raw).map(s => ({ ...s, s: s.reduced ? 0 : 1 })); source = "rule"; }
    if (ov && sylls.length) {
      if (typeof ov === "string") { sylls[sylls.length-1].v = ov; sylls[sylls.length-1].reduced = false; }
      else {
        const n = Math.min(ov.vowels.length, sylls.length);
        for (let i = 0; i < n; i++) {
          const t = sylls[sylls.length-n+i];
          t.v = ov.vowels[i]; t.reduced = false;
          if (ov.stress && ov.stress[i] != null) t.s = ov.stress[i];
        }
        if (ov.coda != null) sylls[sylls.length-1].c = ov.coda;
      }
      source = "override";
    }
    return { sylls, source };
  }
  function skeleton(text, depth = 1, anchor = "count") {
    const words = text.trim().split(/\s+/).filter(Boolean);
    let sylls = [], source = "none";
    for (let i = words.length - 1; i >= 0 && sylls.length < depth + 4; i--) {
      const p = pronounce(words[i]);
      if (i === words.length - 1) source = p.source;
      sylls = [...p.sylls, ...sylls];
    }
    let tail;
    if (anchor === "stress") {
      let k = sylls.length - 1;
      while (k > 0 && !(sylls[k].s > 0)) k--;
      tail = sylls.slice(Math.min(k, sylls.length - depth));
    } else tail = sylls.slice(-depth);
    const last = tail[tail.length-1];
    return { vowels: tail.map(s => s.v), stress: tail.map(s => s.s),
      coda: last ? last.c : "", reduced: last ? !!last.reduced : false,
      overridden: source === "override", source };
  }
  function tailOf(sylls, depth, anchor) {
    let tail;
    if (anchor === "stress") { let k = sylls.length - 1; while (k > 0 && !(sylls[k].s > 0)) k--; tail = sylls.slice(Math.min(k, sylls.length - depth)); }
    else tail = sylls.slice(-depth);
    const last = tail[tail.length-1];
    return { vowels: tail.map(s => s.v), stress: tail.map(s => s.s), coda: last ? last.c : "", reduced: last ? !!last.reduced : false };
  }
  function compare(sa, sb, same) {
    if (!sa.vowels.length || !sb.vowels.length) return "none";
    const n = Math.min(sa.vowels.length, sb.vowels.length);
    const la = sa.vowels.slice(-n), lb = sb.vowels.slice(-n);
    const exact = la.every((v, i) => v === lb[i]) && sa.vowels.length === sb.vowels.length;
    if (!exact) {
      const lastStrict = la[n-1] === lb[n-1];
      if (lastStrict && n > 1 && la.every((v, i) => v === lb[i] || (RED.has(v) && RED.has(lb[i])))) return "loose";
      if (!lastStrict && (sa.reduced || sb.reduced) && RED.has(la[n-1]) && RED.has(lb[n-1])) return "loose";
      return lastStrict ? "shallow" : "none";
    }
    if (same) return "identical";
    return sa.coda === sb.coda ? "perfect" : "slant";
  }
  function classify(a, b, depth = 1, anchor = "count") {
    const sa = skeleton(a, depth, anchor), sb = skeleton(b, depth, anchor);
    if (!sa.vowels.length || !sb.vowels.length) return { kind: "none", sa, sb };
    const n = Math.min(sa.vowels.length, sb.vowels.length);
    const la = sa.vowels.slice(-n), lb = sb.vowels.slice(-n);
    const exact = la.every((v, i) => v === lb[i]) && sa.vowels.length === sb.vowels.length;
    if (!exact) {
      const lastStrict = la[n-1] === lb[n-1];
      const loose = lastStrict && n > 1 && la.every((v, i) => v === lb[i] || (RED.has(v) && RED.has(lb[i])));
      if (loose) return { kind: "loose", sa, sb };
      if (!lastStrict && (sa.reduced || sb.reduced) && RED.has(la[n-1]) && RED.has(lb[n-1])) return { kind: "loose", sa, sb };
      return { kind: lastStrict ? "shallow" : "none", sa, sb };
    }
    if (clean(a) === clean(b)) return { kind: "identical", sa, sb };
    return { kind: sa.coda === sb.coda ? "perfect" : "slant", sa, sb };
  }
  function buildIndex() {
    INDEX = new Map();
    const push = (key, w) => { const l = INDEX.get(key); if (l) l.push(w); else INDEX.set(key, [w]); };
    for (const w of Object.keys(DICT)) {
      if (w.length < 2 || w.includes("'")) continue;
      for (const s of DICT[w].split("|").map(parseOne)) {
        for (let d = 1; d <= Math.min(3, s.length); d++) push(d + ":" + s.slice(-d).map(x => x.v).join("|"), w);
        let k = s.length - 1; while (k > 0 && !(s[k].s > 0)) k--;
        push("S:" + s.slice(k).map(x => x.v).join("|"), w);
      }
    }
  }
  function lookup(query, depth = 1, extra = [], anchor = "stress") {
    const sq = skeleton(query, depth, anchor);
    if (!sq.vowels.length) return { skeleton: sq, reads: [], perfect: [], slant: [], loose: [] };
    const q = clean(query);
    /* a single word with alternate dictionary reads searches on all of them; a phrase or an overridden word searches on its one read */
    const single = !query.trim().includes(" ") && !Object.hasOwn(OVERRIDES, q);
    const qreads = (single && variants(q).length > 1 ? variants(q) : [pronounce(query.trim().split(/\s+/).pop()).sylls]).map(r => tailOf(r, depth, anchor)).filter(t => t.vowels.length);
    const sqs = single && variants(q).length > 1 ? qreads : [sq];
    let cand;
    if (DICT) {
      if (!INDEX) buildIndex();
      cand = new Set([...extra.map(clean), ...OWN]);
      for (const t of sqs) for (const w of INDEX.get((anchor === "stress" ? "S:" : depth + ":") + t.vowels.join("|")) || []) cand.add(w);
    } else cand = new Set([...LEXICON, ...extra.map(clean), ...OWN]);
    const perfect = [], slant = [], loose = [];
    const ORDER = { perfect: 3, slant: 2, loose: 1 };
    for (const w of cand) {
      if (w === q) continue;
      let best = "none";
      const reads = Object.hasOwn(OVERRIDES, w) ? [pronounce(w).sylls] : (variants(w).length ? variants(w) : [pronounce(w).sylls]);
      for (const t of sqs) for (const r of reads) { const k = compare(t, tailOf(r, t.vowels.length, anchor), false); if ((ORDER[k] || 0) > (ORDER[best] || 0)) best = k; }
      const item = { word: w, tier: OWN.has(w) ? 0 : CURATED.has(w) ? 1 : COMMON.has(w) ? 2 : 3, rank: COMMON.get(w) ?? 1e9 };
      if (best === "perfect") perfect.push(item);
      else if (best === "slant") slant.push(item);
      else if (best === "loose") loose.push(item);
    }
    const rank = (a, b) => a.tier - b.tier || a.rank - b.rank || a.word.localeCompare(b.word);
    return { skeleton: sq, reads: sqs.length > 1 ? sqs : [], perfect: perfect.sort(rank), slant: slant.sort(rank), loose: loose.sort(rank) };
  }
  /* mosaic: two-word tails whose joined skeleton matches a multi-syllable query.
   * pool = your words + curated + the top of the frequency list, so the pairs are ones you'd write. */
  let POOL = null;
  function pool() {
    if (POOL) return POOL;
    const words = new Set([...OWN, ...CURATED]);
    for (const [w, r] of COMMON) if (r >= 160 && r < 6000 && w.length > 2) words.add(w);   /* skip the function-word head of the list */
    const byFull = new Map(), byTail = new Map();
    for (const w of words) {
      const reads = variants(w).length ? variants(w) : [pronounce(w).sylls];
      for (const s of reads) {
        if (!s.length || s.length > 3) continue;
        const full = s.map(x => x.v).join("|");
        if (!byFull.has(full)) byFull.set(full, []); byFull.get(full).push({ w, s });
        for (let d = 1; d <= s.length; d++) { const k = d + ":" + s.slice(-d).map(x => x.v).join("|"); if (!byTail.has(k)) byTail.set(k, []); byTail.get(k).push({ w, s }); }
      }
    }
    return POOL = { byFull, byTail };
  }
  function mosaic(query, depth = 2, limit = 40) {
    const sq = skeleton(query, depth, "count");
    const n = sq.vowels.length; if (n < 2) return [];
    const { byFull, byTail } = pool();
    const q = clean(query), out = [], seen = new Set();
    const used = new Set(query.trim().split(/\s+/).map(clean));
    const tierOf = w => OWN.has(w) ? 0 : CURATED.has(w) ? 1 : 2;
    for (let k = 1; k < n; k++) {
      const heads = byTail.get(k + ":" + sq.vowels.slice(0, k).join("|")) || [];
      const tails = byFull.get(sq.vowels.slice(k).join("|")) || [];
      for (const h of heads) for (const t of tails) {
        if (h.w === t.w || used.has(h.w) || used.has(t.w)) continue;
        const key = h.w + " " + t.w; if (seen.has(key)) continue; seen.add(key);
        const kind = compare(sq, tailOf([...h.s.slice(-k), ...t.s], n, "count"), false);
        if (kind === "perfect" || kind === "slant") out.push({ phrase: key, kind, tier: tierOf(h.w) + tierOf(t.w), rank: (COMMON.get(h.w) ?? 9e4) + (COMMON.get(t.w) ?? 9e4) });
      }
    }
    out.sort((a, b) => (a.kind === b.kind ? 0 : a.kind === "perfect" ? -1 : 1) || a.tier - b.tier || a.rank - b.rank);
    return out.slice(0, limit);
  }
  function graph(bars, { window = 8 } = {}) {
    const filled = bars.filter(Boolean);
    const edges = [];
    const tailOf = w => skeleton(w, 1, "stress");
    const link = (a, b, wa, wb, scope) => {
      const ta = tailOf(wa), tb = tailOf(wb);
      if (!ta.vowels.length || !tb.vowels.length) return;
      const depth = Math.max(ta.vowels.length, tb.vowels.length);
      const r = classify(wa, wb, depth, "stress");
      if (r.kind === "perfect" || r.kind === "slant" || r.kind === "loose")
        edges.push({ a, b, kind: r.kind, depth: Math.min(ta.vowels.length, tb.vowels.length), words: [wa, wb], scope });
    };
    for (let i = 0; i < filled.length; i++) {
      const bi = filled[i];
      for (let j = Math.max(0, i - window); j < i; j++) link(filled[j].i, bi.i, filled[j].end.word, bi.end.word, "terminal");
      const inner = bi.field.slice(0, -1).filter(w => w.sylls.some(s => s.s === 1) && !FILLERS.has(w.word.toLowerCase()) && w.word.replace(/[^a-zA-Z]/g, "").length > 2);
      for (const w of inner) {
        const word = w.word.replace(/[^a-zA-Z']/g, "");
        link(bi.i, bi.i, word, bi.end.word, "internal");
        if (i > 0) link(filled[i-1].i, bi.i, filled[i-1].end.word, word, "internal");
      }
    }
    return edges;
  }
  function reading(draft, { pop = "rap" } = {}) {
    const limit = pop === "rap" ? 3 : 6;
    const bars = draft.split("\n").map((ln, i) => {
      const text = ln.trim();
      if (!text) return null;
      const words = text.split(/\s+/);
      /* `s` is lexical stress, straight from the dictionary — rhyme and stress-anchoring read it.
       * `m` is metrical stress: the same value, except a function word demotes to 0 the way it
       * does in a spoken line. Meter scoring reads `m`; nothing that rhymes should touch it. */
      const field = words.map(w => {
        const p = pronounce(w), demoted = FUNCTION_WORDS.has(clean(w));
        return { word: w, source: p.source, sylls: p.sylls.map(s => ({ v: s.v, s: s.s, c: s.c, m: demoted ? 0 : s.s })) };
      });
      const last = words[words.length-1].replace(/[^a-zA-Z']/g, "");
      const end = skeleton(last, 1);
      return { i, text, field, syllables: field.reduce((n, w) => n + w.sylls.length, 0),
        end: { word: last, v: end.vowels[0] || null, coda: end.coda, source: end.source, overridden: end.overridden },
        filler: FILLERS.has(last.toLowerCase()) };
    });
    const runs = []; let cur = null;
    bars.forEach(b => {
      if (!b || !b.end.v) { cur = null; return; }
      if (cur && cur.v === b.end.v) { cur.len++; cur.bars.push(b.i); }
      else { cur = { v: b.end.v, len: 1, bars: [b.i] }; runs.push(cur); }
    });
    const flagged = new Set();
    runs.filter(r => r.len > limit).forEach(r => r.bars.slice(limit).forEach(i => flagged.add(i)));
    const filled = bars.filter(Boolean);
    let terminal = false;
    if (filled.length >= 6) {
      const lastB = filled[filled.length-1], priors = filled.slice(0, -1).slice(-8);
      terminal = lastB.filler || !priors.some(b => b.end.v === lastB.end.v);
    }
    const edges = graph(bars, { window: 8 });
    /* scheme: union-find over terminal edges (perfect + slant); letters in order of first appearance */
    const parent = new Map(filled.map(b => [b.i, b.i]));
    const find = x => { while (parent.get(x) !== x) { parent.set(x, parent.get(parent.get(x))); x = parent.get(x); } return x; };
    edges.filter(e => e.scope === "terminal" && e.kind !== "loose").forEach(e => parent.set(find(e.a), find(e.b)));
    const letters = new Map(); let next = 0;
    filled.forEach(b => { const r = find(b.i); if (!letters.has(r)) letters.set(r, String.fromCharCode(65 + (next++ % 26))); b.scheme = letters.get(r); });
    /* meter drift: a bar that sits ±3 syllables off the median of its neighbours */
    filled.forEach((b, k) => {
      const nb = filled.slice(Math.max(0, k - 2), k).concat(filled.slice(k + 1, k + 3)).map(x => x.syllables).sort((p, q) => p - q);
      if (nb.length < 2) { b.drift = 0; return; }
      const med = nb.length % 2 ? nb[(nb.length - 1) / 2] : (nb[nb.length / 2 - 1] + nb[nb.length / 2]) / 2;
      const d = Math.round(b.syllables - med); b.drift = Math.abs(d) >= 3 ? d : 0;
    });
    return { v: 2, pop, limit, bars, runs, edges, flagged: [...flagged], maxRun: runs.reduce((m, r) => Math.max(m, r.len), 0), terminal };
  }
  /* ---------- meter: score written bars against the template library ----------
   * Diagnostic only — this reads what's there and ranks how it sits, it does not prescribe.
   * Scores the METRICAL pattern (function words demoted), never the lexical one: a line's
   * meter is about which syllables take a beat when spoken, not how each word reads alone.
   *
   * Two components, reported separately because they fail differently and the difference is
   * the useful part: `length` is how close the bar's syllable count sits to the template's,
   * `stress` is how often an accent lands where the template puts one. A bar can be the right
   * length with the accents in the wrong places, or accented right but four syllables short. */
  function fitTemplate(pattern, tpl) {
    const n = Math.min(pattern.length, tpl.stress.length);
    let agree = 0;
    for (let i = 0; i < n; i++) if ((pattern[i] > 0) === (tpl.stress[i] > 0)) agree++;
    const stress = n ? agree / n : 0;
    const length = Math.max(0, 1 - Math.abs(pattern.length - tpl.syllables) / tpl.syllables);
    return { stress, length, score: stress * length };
  }
  function metrical(bar) { return bar.field.flatMap(w => w.sylls.map(s => s.m)); }
  function meter(read) {
    const filled = (read.bars || []).filter(Boolean);
    const rows = filled.map(b => {
      const pattern = metrical(b);
      const all = TEMPLATES.map(t => ({ name: t.name, ...fitTemplate(pattern, t) })).sort((x, y) => y.score - x.score);
      return { i: b.i, text: b.text, syllables: pattern.length, pattern, all, best: all[0] };
    });
    const ranked = TEMPLATES.map(t => {
      const scores = rows.map(r => r.all.find(x => x.name === t.name).score);
      return { name: t.name, syllables: t.syllables, mean: scores.length ? scores.reduce((a, b) => a + b, 0) / scores.length : 0 };
    }).sort((a, b) => b.mean - a.mean);
    const best = ranked[0] || null;
    /* weakest fits under the winning template — ranked, not thresholded, so no invented cutoff
     * decides what counts as "wrong"; the reader sees the spread and judges. */
    const weakest = best
      ? rows.map(r => ({ i: r.i, text: r.text, syllables: r.syllables, ...r.all.find(x => x.name === best.name) }))
          .sort((a, b) => a.score - b.score)
      : [];
    return { rows, ranked, best, weakest, bars: rows.length };
  }
  /* ---------- tempo grid ----------
   * SPINE.md section 11 governs this whole block: THE BEAT IS ARITHMETIC AND MAY BE DESCRIBED; THE
   * PERFORMANCE IS NOT THIS TOOL'S. BPM, time signature, subdivision and - since 2.18 - where a swung
   * pair places its two onsets all follow from numbers a person entered, so the tool may state them.
   * Which slot a syllable actually lands in, whether a writer leans early or late, what a line does in a
   * mouth: none of that is reachable from a draft and none of it is estimated here. A writer writes to
   * the beat; this does not write to the writer, and it never synthesises a performance from what is
   * typed. The guard in engine-node/test/engine.test.js fails the day the public surface grows a
   * syllable-to-onset map, which is the one shape this rule is most likely to be broken by.
   * Arithmetic, not a model. BPM and time signature give a real slot count per bar; nothing
   * here listens to anything or knows how a line is actually performed.
   *
   * `feel` changes how a beat subdivides: straight and swing both cut it in four (swing shifts
   * where the offbeats sit in time, not how many there are), triplet cuts it in three.
   *
   * THAT SENTENCE WAS TRUE OF THE INTENT AND FALSE OF THE CODE until now. SUBDIVISION gave swing
   * and straight the same 4, slotMs was beatMs/per for both, and nothing anywhere carried an
   * onset - so `swing` produced a grid byte-identical to `straight` and differed only by its own
   * label. A feel that names a displacement and displaces nothing is the same class of defect as a
   * conformance table reading "violates: --": the claim outlived the thing it described. Swing is
   * the feel that matters most in the field, so it is the one that had to stop being a label.
   *
   * WHAT SWING IS, sourced rather than invented. Swung subdivisions are the first and third of a
   * triplet: the pair splits 2:1, the long note taking two thirds of it. That is the notated meaning
   * of "swing eighths" and the value MPC-style swing percentage is measured against - 50% straight,
   * 66.7% this. It is a musical convention rather than a property of any substance, so SWING_RATIO
   * is AUTHORED and says so, the same discipline the spine holds for a duration.
   *
   * The displacement applies at the PAIR, and with per = 4 a pair is one eighth split into two
   * sixteenths - sixteenth-note swing, which is where hip-hop puts it. An odd subdivision has no
   * pairs to swing, so triplet returns uniform rather than being silently swung into something else. */
  const SUBDIVISION = { straight: 4, swing: 4, triplet: 3 };
  const SWING_RATIO = 2 / 3;   /* authored: the long note's share of each swung pair */
  /* onset of every slot inside one beat, in ms from the beat - uniform unless swing displaces it */
  function beatOnsets(per, beatMs, feel) {
    if (feel !== "swing" || per % 2) {
      const out = []; for (let i = 0; i < per; i++) out.push(i * beatMs / per); return out;
    }
    const pairs = per / 2, pairMs = beatMs / pairs, out = [];
    for (let p = 0; p < pairs; p++) { out.push(p * pairMs); out.push(p * pairMs + pairMs * SWING_RATIO); }
    return out;
  }
  function grid(bpm = 90, timeSig = "4/4", feel = "straight") {
    const beats = Math.max(1, parseInt(String(timeSig).split("/")[0], 10) || 4);
    const per = SUBDIVISION[feel] || 4;
    const beatMs = 60000 / Math.max(1, bpm);
    const one = beatOnsets(per, beatMs, feel);
    const onsets = [];
    for (let b = 0; b < beats; b++) for (const o of one) onsets.push(b * beatMs + o);
    const swung = feel === "swing" && !(per % 2), pairMs = beatMs / (per / 2);
    return { bpm, timeSig, feel, beats, subdivision: per, slotsPerBar: beats * per, beatMs, onsets,
             swingRatio: swung ? SWING_RATIO : 0.5,
             /* the two durations a swung pair actually has, so a panel can state them instead of
              * implying a uniform slot; equal under straight and triplet, which is how "no swing"
              * says itself honestly */
             longMs: swung ? pairMs * SWING_RATIO : beatMs / per,
             shortMs: swung ? pairMs * (1 - SWING_RATIO) : beatMs / per,
             /* the MEAN slot, named as a mean: under swing no slot has this duration, and the field
              * this replaces claimed every slot did. No product code read it - its only two readers
              * were assertions checking that it tracked bpm, which is true of a mean and was the
              * thing making the uniform-slot claim look verified. A guarded lie is worse than an
              * unguarded one, because the guard is what stops anybody looking again. */
             meanSlotMs: beatMs / per };
  }
  /* How a written bar sits against that grid.
   *
   * `room` is syllable count against available slots — under, exact, or over. Over doesn't mean
   * wrong, it means the line needs finer subdivision than the feel you set.
   *
   * `rate` is the physical one and the most useful: syllables per second required to fit this
   * bar at this tempo. That's checkable against a mouth.
   *
   * Accents are reported as a count and a per-beat density, NOT scored against the beat count.
   * Rap routinely puts several accents in a beat; calling that crowded would flag every bar
   * written. The draft's own spread is the reference — there is no target here to miss. */
  function pace(bar, g) {
    const sylls = bar.field.reduce((n, w) => n + w.sylls.length, 0);
    const accents = bar.field.reduce((n, w) => n + w.sylls.filter(s => s.m > 0).length, 0);
    const slotDelta = sylls - g.slotsPerBar;
    const barSeconds = (g.beatMs * g.beats) / 1000;
    /* ROOM IS NOT EVEN WHEN THE BEAT IS SWUNG, and `rate` is a bar mean that cannot see it. 2.18
     * called that a virtue - "swing changes where, never how many or how fast" - and that is wrong
     * in the way that matters: the writing is not what swings. The BEAT swings, and a line is
     * written against it. So half the slots are short and half are long, and two syllables landing
     * on the short side of a pair have a third less mouth-room than the same two on the long side.
     * A mean over the bar hides exactly the constraint the feel exists to impose.
     *
     * Reported, not modelled. This tool does not know which slot a syllable lands in - that is the
     * writer's ear and the performance's - so it states the room the beat gives and how many slots
     * carry it, and stops there. `tightRate` is the honest ceiling: syllables per second if a pair's
     * worth of them sat on the short side. Nothing here says a line is wrong. */
    const tight = Math.min(g.shortMs, g.longMs);
    return {
      i: bar.i, syllables: sylls, accents,
      slots: g.slotsPerBar, beats: g.beats, slotDelta,
      room: slotDelta === 0 ? "exact" : slotDelta > 0 ? "over" : "under",
      rate: sylls / barSeconds,
      accentsPerBeat: accents / g.beats,
      tightMs: tight,
      even: g.shortMs === g.longMs,
      tightRate: 1000 / tight,
    };
  }
  function tempo(read, opts = {}) {
    const g = grid(opts.bpm, opts.timeSig, opts.feel);
    return { grid: g, bars: (read.bars || []).filter(Boolean).map(b => pace(b, g)) };
  }
  async function load(onChange) {
    if (status === "ready" || status === "loading") return;
    status = "loading"; error = ""; onChange && onChange(status);
    try {
      const [d, f] = await Promise.all([
        fetch("./cmu_skel.json").then(r => { if (!r.ok) throw new Error("cmu_skel.json " + r.status); return r.json(); }),
        fetch("./subtlex_rank.txt").then(r => r.ok ? r.text() : fetch("./google10k.txt").then(r2 => r2.ok ? r2.text() : "")).catch(() => ""),
      ]);
      DICT = d; INDEX = null; POOL = null;
      COMMON = new Map(f.split("\n").filter(Boolean).map((w, i) => [w.trim(), i]));
      status = "ready";
    } catch (e) { status = "error"; error = String(e.message || e); }
    onChange && onChange(status);
  }
  return { pronounce, variants, skeleton, classify, lookup, mosaic, reading, meter, grid, tempo, load, setOwn,
    ready: () => status === "ready", status: () => status, error: () => error,
    size: () => DICT ? Object.keys(DICT).length : LEXICON.length };
})();

