/* AUTO-GENERATED by build.js from tome-src/00_data.js — do not hand-edit, do not hand-copy.
 * Whole file, verbatim: it has no DOM/browser dependency, so it's already Node-safe. */
/* ---------- vowel classes, v1 rule G2P (OOV fallback), curated lexicon, watch lists ---------- */
const VOWEL_COLORS = {
  AY:"#C98A2D", IY:"#5B87A8", EY:"#8FA65B", EH:"#A0703F", AE:"#B04A3A",
  AH:"#9B8AA6", AA:"#C4A35A", OW:"#5E9B8F", UW:"#4C7B9E", AW:"#B5835A",
  OY:"#8A6FA0", ER:"#7D8A6E", OR:"#A6825B", AR:"#B06A4A", IH:"#6E9BA6",
  UH:"#8A8A7A", AIR:"#C9A27A", AO:"#A38A4E",
};
const VOWEL_NAMES = {
  AY:"eye", IY:"ee", EY:"ay", EH:"eh", AE:"a(cat)", AH:"uh", AA:"ah",
  OW:"oh", UW:"oo", AW:"ow", OY:"oy", ER:"er", OR:"or", AR:"ar",
  IH:"i(hit)", UH:"oo(book)", AIR:"air", AO:"aw",
};

/* ---------- G2P: rule-based vowel-skeleton extraction ---------- */
const EXCEPTIONS = {
  me:["IY-"], we:["IY-"], he:["IY-"], she:["IY-"], be:["IY-"], the:["AH0-"],
  here:["IY-R"], near:["IY-R"], dear:["IY-R"], fear:["IY-R"], year:["IY-R"],
  clear:["IY-R"], hear:["IY-R"], appear:["IY-R"], disappear:["IH2-S","AH0-P","IY1-R"],
  tear:["AIR-"], stare:["AIR-"], care:["AIR-"], share:["AIR-"], scare:["AIR-"],
  dare:["AIR-"], rare:["AIR-"], bare:["AIR-"], bear:["AIR-"], wear:["AIR-"],
  swear:["AIR-"], pair:["AIR-"], hair:["AIR-"], fair:["AIR-"], chair:["AIR-"],
  stair:["AIR-"], there:["AIR-"], where:["AIR-"], their:["AIR-"], air:["AIR-"],
  aware:["AIR-"], repair:["AIR-"], despair:["AIR-"], nowhere:["AIR-"],
  both:["OW-TH"], wont:["OW-NT"], dont:["OW-NT"], ghost:["OW-ST"], most:["OW-ST"],
  how:["AW-"], now:["AW-"], cow:["AW-"], vow:["AW-"], wow:["AW-"], allow:["AW-"],
  pull:["UH-L"], full:["UH-L"], bull:["UH-L"], push:["UH-SH"], bush:["UH-SH"],
  hole:["OW-L"], holes:["OW-LZ"], whole:["OW-L"], cold:["OW-LD"], alone:["OW-N"],
  view:["UW-"], views:["UW-Z"], jewel:["UW-L"], jewels:["UW-LZ"], fuel:["UW-L"],
  /* CMUdict lists these initialism/slang readings after a longer letter-spelled variant; pronounce() takes the first, so pin the one people actually say */
  asap:["EY1-","AE2-P"], abs:["AE-BZ"], tac:["AE-K"],
  one:["AH-N"], once:["AH-NS"], two:["UW-"], through:["UW-"], though:["OW-"],
  thought:["AO-T"], enough:["AH-F"], love:["AH-V"], move:["UW-V"],
  come:["AH-M"], some:["AH-M"], done:["AH-N"], none:["AH-N"], gone:["AO-N"],
  blood:["AH-D"], flood:["AH-D"], good:["UH-D"], hood:["UH-D"], wood:["UH-D"],
  could:["UH-D"], would:["UH-D"], should:["UH-D"], put:["UH-T"],
  eye:["AY-"], eyes:["AY-Z"], buy:["AY-"], guy:["AY-"], dry:["AY-"],
  says:["EH-Z"], said:["EH-D"], again:["EH-N"], against:["EH-NST"],
  been:["IH-N"], being:["IY1-","IH0-NG"], friend:["EH-ND"], friends:["EH-NDZ"],
  heart:["AR-T"], hearts:["AR-TS"], great:["EY-T"], break:["EY-K"],
  steak:["EY-K"], dead:["EH-D"], head:["EH-D"], bread:["EH-D"], read:["EH-D"],
  ready:["EH1-D","IY0-"], heavy:["EH1-V","IY0-"], meant:["EH-NT"],
  learn:["ER-N"], earn:["ER-N"], heard:["ER-D"], word:["ER-D"],
  world:["ER-LD"], work:["ER-K"], worse:["ER-S"], worth:["ER-TH"],
  door:["OR-"], floor:["OR-"], more:["OR-"], four:["OR-"], your:["OR-"],
  pour:["OR-"], sure:["OR-"], water:["AO1-T","ER0-"], want:["AO-NT"],
  war:["OR-"], warm:["OR-M"], talk:["AO-K"], walk:["AO-K"], chalk:["AO-K"],
  all:["AO-L"], call:["AO-L"], fall:["AO-L"], small:["AO-L"], ball:["AO-L"],
  always:["AO1-L","EY2-Z"], also:["AO1-L","OW0-"], almost:["AO1-L","OW2-ST"],
  do:["UW-"], to:["UW-"], who:["UW-"], you:["UW-"], shoe:["UW-"],
  lose:["UW-Z"], choose:["UW-Z"], juice:["UW-S"], truth:["UW-TH"],
  give:["IH-V"], live:["IH-V"], gives:["IH-VZ"], liver:["IH1-V","ER0-"],
  have:["AE-V"], gave:["EY-V"], made:["EY-D"], make:["EY-K"],
  they:["EY-"], grey:["EY-"], hey:["EY-"], weight:["EY-T"], eight:["EY-T"],
  height:["AY-T"], light:["AY-T"], night:["AY-T"], right:["AY-T"],
  might:["AY-T"], fight:["AY-T"], sight:["AY-T"], tight:["AY-T"],
  flight:["AY-T"], bright:["AY-T"],
  find:["AY-ND"], mind:["AY-ND"], kind:["AY-ND"], blind:["AY-ND"],
  behind:["AY-ND"], wild:["AY-LD"], child:["AY-LD"],
  cool:["UW-L"], pool:["UW-L"], fool:["UW-L"], school:["UW-L"], rule:["UW-L"],
  rules:["UW-LZ"], tool:["UW-L"], jewel:["UW-L"],
  money:["AH1-N","IY0-"], honey:["AH1-N","IY0-"], monday:["AH1-N","EY0-"],
  nothing:["AH1-TH","IH0-NG"], something:["AH1-M","IH0-NG"], brother:["AH1-TH","ER0-"],
  mother:["AH1-TH","ER0-"], other:["AH1-TH","ER0-"], another:["AH1-TH","ER0-"],
  cover:["AH1-V","ER0-"], above:["AH-V"], oven:["AH1-V","AH0-N"],
  people:["IY1-P","AH0-L"], police:["OW1-L","IY0-S"],
  phone:["OW-N"], home:["OW-M"], zone:["OW-N"], throne:["OW-N"],
  alone:["OW-N"], bone:["OW-N"], stone:["OW-N"], known:["OW-N"],
  grown:["OW-N"], shown:["OW-N"], own:["OW-N"],
  gun:["AH-N"], guns:["AH-NZ"], young:["AH-NG"], tongue:["AH-NG"],
  front:["AH-NT"], month:["AH-NTH"], among:["AH-NG"],
  does:["AH-Z"], was:["AH-Z"], what:["AH-T"], from:["AH-M"], of:["AH-V"],
  off:["AO-F"], on:["AO-N"], wrong:["AO-NG"], long:["AO-NG"], song:["AO-NG"],
  strong:["AO-NG"], gang:["AE-NG"], thing:["IH-NG"], king:["IH-NG"],
  ring:["IH-NG"], bring:["IH-NG"], chain:["EY-N"], rain:["EY-N"],
  pain:["EY-N"], game:["EY-M"], name:["EY-M"], fame:["EY-M"], same:["EY-M"],
  flame:["EY-M"], shame:["EY-M"], blame:["EY-M"], came:["EY-M"],
  lane:["EY-N"], plane:["EY-N"], insane:["EY-N"], stay:["EY-"],
  way:["EY-"], day:["EY-"], say:["EY-"], play:["EY-"], pay:["EY-"],
  away:["EY-"], okay:["EY-"], today:["EY-"],
  high:["AY-"], sky:["AY-"], fly:["AY-"], why:["AY-"], try:["AY-"],
  cry:["AY-"], die:["AY-"], lie:["AY-"], tie:["AY-"], my:["AY-"],
  by:["AY-"], i:["AY-"], time:["AY-M"], climb:["AY-M"], dime:["AY-M"],
  crime:["AY-M"], prime:["AY-M"], rhyme:["AY-M"], line:["AY-N"],
  fine:["AY-N"], mine:["AY-N"], shine:["AY-N"], sign:["AY-N"],
  design:["AY-N"], nine:["AY-N"], wine:["AY-N"], ride:["AY-D"],
  side:["AY-D"], slide:["AY-D"], pride:["AY-D"], inside:["AY-D"],
  outside:["AY-D"], life:["AY-F"], knife:["AY-F"], wife:["AY-F"],
  ice:["AY-S"], nice:["AY-S"], price:["AY-S"], twice:["AY-S"], dice:["AY-S"],
  drank:["AE-NGK"], saran:["AE-N"], star:["AR-"], car:["AR-"], far:["AR-"],
  bar:["AR-"], scar:["AR-"], cigar:["AR-"], guitar:["AR-"],
  dark:["AR-K"], park:["AR-K"], spark:["AR-K"], heart2:["AR-T"],
  start:["AR-T"], part:["AR-T"], smart:["AR-T"], art:["AR-T"],
  hard:["AR-D"], card:["AR-D"], yard:["AR-D"], guard:["AR-D"],
};
const DIGRAPHS = [
  ["igh","AY",""],["eigh","EY",""],["ough","OW",""],["augh","AO",""],
  ["tion","SH-AH-N","*"],["sion","ZH-AH-N","*"],
  ["oo","UW",""],["ee","IY",""],["ea","IY",""],["ai","EY",""],["ay","EY",""],
  ["oa","OW",""],["ow","OW",""],["ou","AW",""],["oi","OY",""],["oy","OY",""],
  ["au","AO",""],["aw","AO",""],["ew","UW",""],["ue","UW",""],["ui","UW",""],
  ["ie","IY",""],["ey","IY",""],
];
const LETTERS = { a:["EY",""], b:["IY",""], c:["IY",""], d:["IY",""], e:["IY",""],
  f:["EH","F"], g:["IY",""], h:["EY","CH"], i:["AY",""], j:["EY",""], k:["EY",""],
  l:["EH","L"], m:["EH","M"], n:["EH","N"], o:["OW",""], p:["IY",""], q:["UW",""],
  r:["AR",""], s:["EH","S"], t:["IY",""], u:["UW",""], v:["IY",""], w:["UW",""],
  x:["EH","KS"], y:["AY",""], z:["IY",""] };
function g2p(raw) {
  // initialism: all-caps token with no vowel letters -> letter names (PBM, DM)
  const caps = raw.replace(/[^A-Za-z]/g, "");
  if (caps && caps === caps.toUpperCase() && caps.length <= 4 &&
      !/[AEIOU]/.test(caps)) {
    return caps.toLowerCase().split("").map(ch => {
      const [v, c] = LETTERS[ch] || ["AH", ""]; return { v, c };
    });
  }
  const w = raw.toLowerCase().replace(/[^a-z']/g, "");
  if (!w) return [];
  if (EXCEPTIONS[w]) return EXCEPTIONS[w].map(s => {
    const [raw, c] = s.split("-");
    return { v: raw.replace(/\d$/, ""), c: c || "" };   // strip the stress tag; g2p's callers only want the vowel class
  });
  let s = w.replace(/'/g, "");
  let suffix = "";
  const m = s.match(/^(.+[^aeiou])e([sd])$/);   // holes, stared, names
  if (m && !/(s|x|z|ch|sh)e[sd]$/.test(s) && m[1].length > 1) {
    suffix = m[2]; s = m[1] + "e";
  }
  // final silent e (not -le)
  if (s.length > 2 && s.endsWith("e") && !"aeiou".includes(s[s.length-2]) &&
      s[s.length-2] !== "l") {
    s = s.slice(0, -1) + "\u0001"; // magic-e marker lengthens prior vowel
  }
  s += suffix;
  const sylls = [];
  let i = 0, coda = "";
  const pushV = (v) => { sylls.push({ v, c: "" }); coda = ""; };
  while (i < s.length) {
    let matched = false;
    for (const [g, v] of DIGRAPHS) {
      if (s.startsWith(g, i)) {
        pushV(v.includes("-") ? v.split("-")[1] : v);
        if (v.includes("-")) sylls[sylls.length-1].c = "N";
        i += g.length; matched = true; break;
      }
    }
    if (matched) continue;
    const ch = s[i];
    if ("aeiouy".includes(ch) && !(ch === "y" && i === 0)) {
      const nxt = s[i+1] || "", nn = s[i+2] || "";
      const magic = nxt === "\u0001" || nn === "\u0001" ||
        (i+2 < s.length && !"aeiou\u0001".includes(nxt) && (nn === "e" && i+2 === s.length-1));
      const rnext = nxt === "r";
      let v;
      if (ch === "a") v = rnext ? "AR" : magic ? "EY" : "AE";
      else if (ch === "e") v = rnext ? "ER" : magic ? "IY" : "EH";
      else if (ch === "i") v = rnext ? "ER" : magic ? "AY" : "IH";
      else if (ch === "o") v = rnext ? "OR" : magic ? "OW" : "AA";
      else if (ch === "u") v = rnext ? "ER" : magic ? "UW" : "AH";
      else if (ch === "y") v = i === s.length-1 ? (s.length <= 3 ? "AY" : "IY") : "IH";
      pushV(v);
      if (rnext) i++; // consume the r into the vowel class
      i++;
    } else if (ch === "\u0001") { i++; }
    else {
      if (sylls.length) sylls[sylls.length-1].c += ch.toUpperCase();
      i++;
    }
  }
  // final-schwa reduction: unstressed -an/-en/-on/-ain/-ern tails on 2+ syllable
  // words read as schwa in the mouth (Michigan, Dayton, haven)
  if (sylls.length >= 2) {
    const last = sylls[sylls.length-1];
    if (/(?:[aeo]n|ain|ern)$/.test(w) && ["AE","AA","EH","IH","EY"].includes(last.v) &&
        /^N/.test(last.c || "N") ) {
      last.v = "AH"; last.reduced = true;
      if (!last.c) last.c = "N";
    } else if (/a s?$/.test(w + " ") && ["AE","AA"].includes(last.v) && !last.c) {
      last.v = "AH"; last.reduced = true;   // wanna, jorjiana, benihanna(s)
    } else if (/as$/.test(w) && ["AE","AA"].includes(last.v) && last.c === "S") {
      last.v = "AH"; last.reduced = true;   // forgiatas, benihannas
    }
  }
  return sylls.length ? sylls : [{ v: "AH", c: "" }];
}
const LEX_RAW = `time mind grind shine line fine mine sign design vine spine climb dime crime prime rhyme lime ride side slide pride tide wide hide guide life knife wife strife ice nice price twice vice dice rice fly sky high why try cry die lie tie eye guy buy dry supply deny reply alive drive five hive strive thrive fire desire entire wire tire liar higher flyer light night right might fight sight tight flight bright white kite quite write bite site find kind blind behind wild child mild style mile smile while trial file pile
see me free three key tree sea knee flee degree agree decree spree bee fee tea plea weak speak leak peak sneak freak unique clique streak seat heat beat street sweet complete elite receipt deep sleep keep creep steep leap cheap heap reap dream team scheme cream steam beam gleam scene clean mean lean green queen seen between machine routine believe leave weave grieve achieve receive breathe need feed speed greed bleed indeed succeed
day way say play pay stay away okay today lane plane insane chain rain pain gain main brain drain train remain complain explain game name fame same flame shame blame came frame claim aim maim fade shade blade grade made paid afraid parade wave cave save brave crave slave gave behave grave rage page cage stage wage engage sage race place face space chase base case grace erase taste waste paste haste eight weight great late gate hate fate state rate create relate debate plate skate crate
bed head dead red said bread thread spread instead fed led shed sled wed dread stress mess less bless press confess address progress possess best rest test chest quest west vest invest arrest suggest request blessed left theft depth met set bet get jet let net pet sweat threat regret upset forget check neck wreck deck respect connect direct effect protect reflect collect perfect
cat hat bat flat mat rat sat chat brat splat back black track pack rack stack attack snack crack lack sack whack act fact pact react impact intact exact attract abstract bag tag flag drag swag brag snag rag hand band land sand stand brand grand demand command expand man plan can ban fan ran span scan clan than bran gram slam jam ham damn program madam bad mad sad glad add pad had grab stab tab lab cab crab trap map slap clap snap gap wrap strap cap app
cut but shut what gut hut nut strut mud blood flood bud stud dud sun run fun gun done none one son ton won stun begun shun undone drum come some numb dumb thumb crumb plum slum succumb love above dove glove shove enough tough rough stuff bluff cuff huff puff buzz was does fuzz cuz because bus plus us trust must dust bust rust crust adjust disgust discuss luck stuck truck buck duck struck
hot not shot spot got lot plot knot rot slot forgot pot dot block clock rock shock knock stock lock dock mock top stop drop shop cop pop prop crop flop swap job rob mob knob sob blob problem body copy stop2
go show know low flow grow slow blow snow throw glow row toe foe pro bro tho so no mo dough although road load code mode explode erode episode boat coat float note wrote quote vote throat remote goat gold cold bold hold told sold fold old mold behold bone phone zone throne alone stone known grown shown own home dome chrome roam foam comb close chose rose those nose pose suppose expose froze hole whole role soul goal coal control patrol stroll roll toll bowl
you too blue true new few crew flew grew knew threw view due sue clue glue shoe who through screw tattoo pursue avenue school cool pool fool tool rule jewel fuel cruel duel move prove groove smooth booth truth youth roof proof group loop scoop troop hoop soup loot boot shoot root fruit suit pursuit recruit flute brute mute cute acute dispute salute food mood dude rude crude conclude include attitude gratitude solitude
now how cow wow allow vow plow brow chow down town crown brown drown frown gown clown around sound found ground round pound bound mound astound profound out about shout doubt route scout clout drought loud cloud proud crowd allowed house mouse blouse
her stir sir fur blur slur occur prefer transfer defer refer confer turn burn learn earn yearn stern concern return word bird third heard herd nerd absurd hurt dirt shirt skirt flirt alert convert insert expert desert dessert work jerk clerk lurk perk smirk verse curse worse nurse purse rehearse reverse universe first burst thirst worst world girl curl hurl pearl swirl twirl
star car far bar scar jar tar spar cigar guitar bizarre dark park spark mark shark stark remark heart start part smart art chart apart depart hard card yard guard regard bombard arm charm farm harm alarm army bar2
door floor more four your pour score store shore before ignore explore restore adore galore bore core tore wore swore snore chore war warm form storm norm transform inform perform swarm born corn torn worn horn sworn adorn forlorn short sport court fort port report support resort escort north force source horse course divorce endorse remorse
boy toy joy enjoy destroy employ annoy deploy alloy decoy soy coy
drip trip grip flip clip whip ship hip lip rip sip tip zip skip strip equip chip snip vip win sin thin spin skin grin pin chin twin begin within bin fin gin big dig pig rig wig fig gig twig swig zig hit sit fit bit kit lit mitt quit spit split legit admit commit permit submit transmit sick quick thick trick brick click flick lick pick slick stick wick kick chick nick still hill will bill chill fill grill skill spill thrill drill mill pill will2 gill ill instill until fulfill
brick flick trick2 rich which switch pitch ditch snitch witch glitch stitch itch twitch
plug drug thug rug bug hug mug jug snug shrug tug slug smug
cash flash trash smash crash stash splash dash bash gash sash clash flash2
bank tank rank blank thank crank frank prank drank sank shrank spank plank
cheese please breeze freeze squeeze seize tease ease disease trees keys seas fleas
paper vapor labor favor flavor neighbor savior behavior
water daughter slaughter quarter mortar order border corner
lean bean dean gene keen teen preen serene obscene careen canteen thirteen fourteen fifteen sixteen eighteen nineteen caffeine gasoline magazine submarine tangerine vaseline guillotine limousine
pint grind2 behind2
brr skrt racks stacks packs tracks lacs facts wax tax max relax flex checks necks
opps cops glocks blocks knots shots spots plots watts
whip2 wraith ghost most host coast toast boast roast post
mob rob2 job2 slob heartthrob
lit2 gucci louis prada nada collada armada
geeked leaked peaked tweaked freaked sneaked
wave2 gang lang slang bang hang rang sprang fang overhang boomerang
codeine lean2 serene2 machine2
juice loose goose deuce noose truce moose reduce produce seduce introduce excuse abuse confuse refuse amuse
paid2 blade2 fade2 jade shade2 upgrade renegade grenade lemonade cascade charade blockade brigade crusade
racks2 bands grands lands hands stands brands sands demands commands
whoa2 flow2 dough2 bro2 loco solo polo logo promo photo motto lotto ghetto
mansion expansion action fraction traction attraction satisfaction transaction distraction passion fashion compassion
vision decision collision precision incision division provision revision television
paranoid void avoid android steroid
diamond diamonds
molly lolly dolly holly jolly volley trolley
benjamins benjamin
hunnid hunnids
`;
const LEXICON = [...new Set(
  LEX_RAW.split(/\s+/).map(w => w.replace(/\d+$/, "")).filter(w => w.length > 1)
)];
const FILLERS = new Set(["you","too","to","that","it","them","me","a","the","at",
  "of","for","and","so","on","in","up","do"]);

/* ---------- function words, for metrical (not lexical) stress ----------
 * The dictionary gives citation stress — each word said alone, where "you" and "was"
 * are stressed. Meter is a property of the line, where those reduce. reading() uses this
 * set to demote them into a second stress field; the lexical `s` rhyme depends on is left alone.
 *
 * Deliberately conservative. Words whose function/content use is genuinely ambiguous without
 * part-of-speech tagging are LEFT OUT rather than guessed at, because a wrong metrical read is
 * worse than a missing one: particles (up, out, off, over, through), deictics (this, these,
 * here, there), quantifiers (some, any, no), modals (will, would, can, could, should), and
 * standalone possessives (mine, yours, hers, theirs) all carry beats often enough in this
 * register to leave alone. Tune this set — it's the one knob metrical scoring turns on. */
const FUNCTION_WORDS = new Set([
  "a","an","the",
  "of","to","in","at","on","by","for","with","from","into","onto","upon","about",
  "i","me","my","you","your","he","him","his","she","her","it","its","we","us","our","they","them","their",
  "am","is","are","was","were","be","been","being","do","does","did","have","has","had",
  "and","or","but","as","than","that","if","so",
]);

module.exports = { g2p, EXCEPTIONS, LETTERS, LEXICON, FILLERS, FUNCTION_WORDS, VOWEL_NAMES, VOWEL_COLORS };
