/* AUTO-GENERATED by build.js from tome-src/10_engine.js — do not hand-edit, do not hand-copy. */
/* ---------- storage v2, with a one-time carry from the metro keys ---------- */
const STORE = {
  get(k, fb) { try { const r = localStorage.getItem("tome:" + k); return r ? JSON.parse(r) : fb; } catch (e) { return fb; } },
  set(k, v) { try { localStorage.setItem("tome:" + k, JSON.stringify(v)); } catch (e) {} },
  migrate() {
    try {
      if (localStorage.getItem("tome:migrated")) return false;
      const old = k => { const r = localStorage.getItem("ghostcodex:" + k); return r ? JSON.parse(r) : null; };
      const bank = old("bank"), draft = old("draft"), ov = old("overrides"), mp = old("metroprefs");
      if (bank) STORE.set("bank", bank);
      if (draft) STORE.set("shelf", [{ id: "carried", name: "carried draft", text: draft, updated: Date.now() }]);
      if (draft) STORE.set("current", "carried");
      if (ov) STORE.set("overrides", ov);
      if (mp) STORE.set("prefs", { mineral: mp.accent === "slime" ? "malachite" : "amethyst", density: mp.density || "comfy", motion: mp.motion || "on" });
      localStorage.setItem("tome:migrated", "1");
      return !!(bank || draft || ov);
    } catch (e) { return false; }
  },
};


module.exports = { STORE };
