#!/usr/bin/env node
/* build.js — assembles tome-src/{00_data.js, 10_engine.js, 20_style.css, 25_card.js, 30_ui.jsx}
 * into dist/index.html, and extracts the browser-safe blocks that engine-node/ needs into
 * their own requireable files, so they can never hand-drift from the shipped source:
 *   - engine-node/rule_g2p_v1.js  <- tome-src/00_data.js (whole file — no DOM/browser APIs in it)
 *   - engine-node/engine_core.js  <- tome-src/10_engine.js, the "engine 2.0" block
 *   - engine-node/store_core.js   <- tome-src/10_engine.js, the "storage v2" block
 *
 * Usage: node build.js
 * Requires: node >= 18. No npm dependencies.
 */
const fs = require("fs");
const path = require("path");
const babel = require("@babel/core");
const SRC = path.join(__dirname, "tome-src");
const DIST = path.join(__dirname, "dist");
const ENODE = path.join(__dirname, "engine-node");

const data = fs.readFileSync(path.join(SRC, "00_data.js"), "utf8");
const engine = fs.readFileSync(path.join(SRC, "10_engine.js"), "utf8");
const css = fs.readFileSync(path.join(SRC, "20_style.css"), "utf8");
const card = fs.readFileSync(path.join(SRC, "25_card.js"), "utf8");
const ui = fs.readFileSync(path.join(SRC, "30_ui.jsx"), "utf8");

for (const [name, blob] of [["00_data.js", data], ["10_engine.js", engine], ["25_card.js", card], ["30_ui.jsx", ui]]) {
  if (blob.includes("</script")) throw new Error(`${name} contains a literal "</script" — this breaks the assembled HTML. Escape it (e.g. "<\\/script").`);
  // Babel Standalone compiles this in-browser at load time with zero syntax feedback beyond a
  // blank page; catch a broken file here instead, with the same JSX/preset-react it'll actually run under.
  try {
    babel.transform(blob, { presets: [require.resolve("@babel/preset-react")], filename: name });
  } catch (e) {
    throw new Error(`${name} does not parse as valid JS/JSX — this would ship a blank page. ${e.message}`);
  }
}

function between(text, startMarker, endMarker, label) {
  const s = text.indexOf(startMarker);
  if (s === -1) throw new Error(`${label}: start marker not found — ${JSON.stringify(startMarker)}`);
  const e = text.indexOf(endMarker, s + startMarker.length);
  if (e === -1) throw new Error(`${label}: end marker not found — ${JSON.stringify(endMarker)}`);
  return text.slice(s, e);
}

/* ---------- engine-node extraction (fails loud if the source markers move) ---------- */
const ENGINE_START = "/* ---------- engine 2.0 ---------- */";
const STORE_START = "/* ---------- storage v2, with a one-time carry from the metro keys ---------- */";
const SUNDIAL_START = "/* ---------- sundial:";

const engineCore = between(engine, ENGINE_START, STORE_START, "10_engine.js -> engine_core.js");
const storeCore = between(engine, STORE_START, SUNDIAL_START, "10_engine.js -> store_core.js");

fs.mkdirSync(ENODE, { recursive: true });
fs.writeFileSync(path.join(ENODE, "engine_core.js"),
  `/* AUTO-GENERATED by build.js from tome-src/10_engine.js — do not hand-edit, do not hand-copy. */\n${engineCore}`);
fs.writeFileSync(path.join(ENODE, "store_core.js"),
  `/* AUTO-GENERATED by build.js from tome-src/10_engine.js — do not hand-edit, do not hand-copy. */\n${storeCore}\nmodule.exports = { STORE };\n`);
fs.writeFileSync(path.join(ENODE, "rule_g2p_v1.js"),
  `/* AUTO-GENERATED by build.js from tome-src/00_data.js — do not hand-edit, do not hand-copy.\n * Whole file, verbatim: it has no DOM/browser dependency, so it's already Node-safe. */\n${data}\nmodule.exports = { g2p, EXCEPTIONS, LETTERS, LEXICON, FILLERS, FUNCTION_WORDS, TEMPLATES, VOWEL_NAMES, VOWEL_COLORS };\n`);

/* ---------- dist/index.html assembly ---------- */
const html = `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="theme-color" content="#4f3a1c">
<meta name="apple-mobile-web-app-title" content="rhyme">
<link rel="apple-touch-icon" href="./icon-180.png">
<link rel="icon" type="image/png" sizes="192x192" href="./icon-192.png">
<link rel="manifest" href="./manifest.json">
<title>rhyme instrument — tome</title>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react/18.3.1/umd/react.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/react-dom/18.3.1/umd/react-dom.production.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/babel-standalone/7.26.4/babel.min.js"></script>
<style>
${css}
</style>
</head>
<body>
<div id="root"></div>
<script>if ("serviceWorker" in navigator) addEventListener("load", () => navigator.serviceWorker.register("./sw.js").catch(() => {}));</script>
<script type="text/babel" data-presets="react">
/* ghost codex · rhyme instrument · tome — v2.3.1 tome — assembled by build.js, do not hand-edit */
${data}
${engine}
${card}
${ui}
</script>
</body>
</html>
`;

fs.mkdirSync(DIST, { recursive: true });
fs.writeFileSync(path.join(DIST, "index.html"), html);
for (const f of ["sw.js", "manifest.json", "icon-180.png", "icon-192.png", "icon-512.png"]) {
  fs.copyFileSync(path.join(SRC, f), path.join(DIST, f));
}
console.log(`built dist/index.html (${html.length.toLocaleString()} bytes) + sw.js, manifest.json, 3 icons.`);
console.log(`regenerated engine-node/{engine_core.js, store_core.js, rule_g2p_v1.js} from tome-src.`);
console.log(`cmu_skel.json, subtlex_rank.txt, google10k.txt live permanently at the repo root — not part of this build, not touched by it.`);
