#!/usr/bin/env node
/* build.js — assembles tome-src/{00_data.js, 10_engine.js, 20_style.css, 25_card.js, 30_ui.jsx}
 * into dist/index.html, and extracts the browser-safe blocks that engine-node/ needs into
 * their own requireable files, so they can never hand-drift from the shipped source:
 *   - engine-node/rule_g2p_v1.js  <- tome-src/00_data.js (whole file — no DOM/browser APIs in it)
 *   - engine-node/engine_core.js  <- tome-src/10_engine.js, the "engine 2.0" block
 *   - engine-node/store_core.js   <- tome-src/10_engine.js, the "storage v2" block
 *
 * Usage: node build.js
 * Requires: node >= 18. No npm dependencies.
 */
const fs = require("fs");
const path = require("path");
const babel = require("@babel/core");
const SRC = path.join(__dirname, "tome-src");
const DIST = path.join(__dirname, "dist");
const ENODE = path.join(__dirname, "engine-node");

const data = fs.readFileSync(path.join(SRC, "00_data.js"), "utf8");
const engine = fs.readFileSync(path.join(SRC, "10_engine.js"), "utf8");
const css = fs.readFileSync(path.join(SRC, "20_style.css"), "utf8");
const card = fs.readFileSync(path.join(SRC, "25_card.js"), "utf8");
const ui = fs.readFileSync(path.join(SRC, "30_ui.jsx"), "utf8");

/* OCCVM-D4 / roadmap 1.6 — the transpile is EMITTED, not discarded.
 *
 * Until 1.6 this loop ran babel over every block purely to validate it, threw the output away, and
 * shipped the untranspiled source for babel-standalone to compile again in the visitor's browser. That
 * was a 2.98 MB runtime compiler doing at load time what had already been done here. It is gone.
 */
const COMPILED = {};
for (const [name, blob] of [["00_data.js", data], ["10_engine.js", engine], ["25_card.js", card], ["30_ui.jsx", ui]]) {
  if (blob.includes("</script")) throw new Error(`${name} contains a literal "</script" — this breaks the assembled HTML. Escape it (e.g. "<\\/script").`);
  try {
    COMPILED[name] = babel.transform(blob, { presets: [require.resolve("@babel/preset-react")], filename: name }).code;
  } catch (e) {
    throw new Error(`${name} does not parse as valid JS/JSX — this would ship a blank page. ${e.message}`);
  }
  if (COMPILED[name].includes("</script")) throw new Error(`${name}: transpiled output contains a literal "</script".`);
}

/* React and ReactDOM are inlined from vendor/, pinned and committed. Roadmap 1.6's exit is that first
 * paint shows the binding, not a blank frame, and that no tool installs to a home screen it cannot
 * serve — neither holds while the runtime is fetched from a CDN. The artifact is now self-contained:
 * zero external requests, which is also what makes the service worker's shell complete. */
const VENDOR = path.join(__dirname, "vendor");
const REACT = ["react-18.3.1.umd.min.js", "react-dom-18.3.1.umd.min.js"].map(f => {
  const p = path.join(VENDOR, f);
  if (!fs.existsSync(p)) throw new Error(`vendor/${f} is missing — see vendor/README.md`);
  const blob = fs.readFileSync(p, "utf8");
  if (blob.includes("</script")) throw new Error(`vendor/${f} contains a literal "</script".`);
  return { f: f, blob: blob };
});

function between(text, startMarker, endMarker, label) {
  const s = text.indexOf(startMarker);
  if (s === -1) throw new Error(`${label}: start marker not found — ${JSON.stringify(startMarker)}`);
  const e = text.indexOf(endMarker, s + startMarker.length);
  if (e === -1) throw new Error(`${label}: end marker not found — ${JSON.stringify(endMarker)}`);
  return text.slice(s, e);
}

/* ---------- engine-node extraction (fails loud if the source markers move) ---------- */
const ENGINE_START = "/* ---------- engine 2.0 ---------- */";
const STORE_START = "/* ---------- storage v2, with a one-time carry from the metro keys ---------- */";
const SUNDIAL_START = "/* ---------- sundial:";

const engineCore = between(engine, ENGINE_START, STORE_START, "10_engine.js -> engine_core.js");
const storeCore = between(engine, STORE_START, SUNDIAL_START, "10_engine.js -> store_core.js");

fs.mkdirSync(ENODE, { recursive: true });
fs.writeFileSync(path.join(ENODE, "engine_core.js"),
  `/* AUTO-GENERATED by build.js from tome-src/10_engine.js — do not hand-edit, do not hand-copy. */\n${engineCore}`);
fs.writeFileSync(path.join(ENODE, "store_core.js"),
  `/* AUTO-GENERATED by build.js from tome-src/10_engine.js — do not hand-edit, do not hand-copy. */\n${storeCore}\nmodule.exports = { STORE };\n`);
fs.writeFileSync(path.join(ENODE, "rule_g2p_v1.js"),
  `/* AUTO-GENERATED by build.js from tome-src/00_data.js — do not hand-edit, do not hand-copy.\n * Whole file, verbatim: it has no DOM/browser dependency, so it's already Node-safe. */\n${data}\nmodule.exports = { g2p, EXCEPTIONS, LETTERS, LEXICON, FILLERS, FUNCTION_WORDS, TEMPLATES, VOWEL_NAMES, VOWEL_COLORS };\n`);

/* ---------- build stamp ----------
 * The deployed artifact carried no stamp of any kind, so there was no way to tell which build a host
 * was serving — the check every deploy procedure in the sibling BTC repo depends on
 * (grep -o 'build-[0-9]\{14\}'), and the ledger law the OCCVM roadmap states.
 *
 * Minting was deliberate and manual: `node build.js --stamp` minted, a plain `node build.js` preserved
 * whatever the committed index.html already carried. That keeps CI's byte-identical regeneration check
 * strict — a timestamp minted on every run would make the diff spurious and teach everyone to ignore it
 * (2.0 migration process, section 0b rule 4).
 *
 * 2.30 — IT NOW MINTS WHEN THE CONTENT CHANGED, and that is a defect fix rather than a convenience.
 * Preserve-unless-asked is right for iteration and wrong at the one boundary it cannot see: a deploy.
 * Measured on this repository — `build-20260910054846` was minted at 2.27 and then carried, unchanged,
 * through 2.28 and its steps 3, 4+5 and 6, because every build after the first was a plain one. The
 * host served four releases of content under one stamp. That is not a cosmetic slip: verifying a deploy
 * by stamp is the whole procedure the sibling repo's section 1 step 4 states, and a stamp that does not
 * move with the content makes that check answer yes to a question it never asked.
 *
 * The rule that replaces "remember the flag" is the condition itself: compare this build's output
 * against the committed artifact WITH BOTH STAMPS MASKED. Identical content keeps its stamp, so the
 * regeneration diff stays byte-clean and CI stays strict; changed content mints, so a stamp always
 * identifies what it stamps. `--stamp` still forces one, and `--keep-stamp` forces the old behaviour
 * for the case this cannot know about — re-cutting an identical artifact deliberately.
 */
const STAMP_RE = /build-\d{14}/g;
const STAMP = (() => {
  const mint = () => "build-" + new Date().toISOString().replace(/\D/g, "").slice(0, 14);
  if (process.argv.includes("--stamp")) return mint();
  let prior = null, committed = null;
  try {
    committed = fs.readFileSync(path.join(__dirname, "index.html"), "utf8");
    const m = committed.match(STAMP_RE);
    if (m) prior = m[0];
  } catch (e) {}
  if (!prior) return mint();
  if (process.argv.includes("--keep-stamp")) return prior;
  /* Assemble once under the prior stamp and compare masked. `assemble` is the same function the real
     build uses, so this cannot drift from what ships — a second copy of the assembly would be the
     defect this whole file exists downstream of. */
  try {
    const trial = assemble(prior).replace(STAMP_RE, "");
    if (trial === committed.replace(STAMP_RE, "")) return prior;   /* nothing changed: keep it */
  } catch (e) {}
  return mint();
})();

/* ---------- dist/index.html assembly ----------
 * A FUNCTION rather than a bare template, so the stamp block above can assemble a trial copy through
 * exactly this code. A second copy of the assembly, written to answer "did anything change?", would be
 * two sources of truth for what ships — the defect class this repository keeps finding — and it would
 * drift the first time a line was added here and not there. Hoisted, and every value it reads is
 * initialised well above the stamp block that calls it. */
function assemble(stamp) { return `<!doctype html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, viewport-fit=cover">
<meta name="apple-mobile-web-app-capable" content="yes">
<meta name="apple-mobile-web-app-status-bar-style" content="black-translucent">
<meta name="theme-color" content="#4f3a1c">
<meta name="apple-mobile-web-app-title" content="rhyme">
<link rel="apple-touch-icon" href="./icon-180.png">
<link rel="icon" type="image/png" sizes="192x192" href="./icon-192.png">
<link rel="manifest" href="./manifest.json">
<title>rhyme instrument — tome</title>
<style>
${css}
</style>
</head>
<body>
<div id="root"></div>
<script>if ("serviceWorker" in navigator) addEventListener("load", () => navigator.serviceWorker.register("./sw.js").catch(() => {}));</script>
${REACT.map(r => `<script>/* vendor/${r.f} — pinned, committed, inlined. see vendor/README.md */\n${r.blob}</script>`).join("\n")}
<script>
/* ghost codex · rhyme instrument · tome — v2.4 — assembled and transpiled by build.js, do not hand-edit.
   JSX is compiled here, at author time, not in the visitor's browser (OCCVM-D4, roadmap 1.6). */
${COMPILED["00_data.js"]}
${COMPILED["10_engine.js"]}
${COMPILED["25_card.js"]}
${COMPILED["30_ui.jsx"]}
</script>
</body>
<!-- ${stamp} -->
</html>
`; }

const html = assemble(STAMP);

fs.mkdirSync(DIST, { recursive: true });
fs.writeFileSync(path.join(DIST, "index.html"), html);
/* sw.js is templated, not copied: its cache name is the build stamp, so a deploy cannot ship a new page
   behind a cache name that still looks current (roadmap 1.6). */
const sw = fs.readFileSync(path.join(SRC, "sw.js"), "utf8");
if (!sw.includes("__BUILD_STAMP__")) throw new Error("tome-src/sw.js lost its __BUILD_STAMP__ placeholder — the cache name would not track the build");
fs.writeFileSync(path.join(DIST, "sw.js"), sw.split("__BUILD_STAMP__").join(STAMP));
for (const f of ["manifest.json", "icon-180.png", "icon-192.png", "icon-512.png"]) {
  fs.copyFileSync(path.join(SRC, f), path.join(DIST, f));
}
console.log(`built dist/index.html (${html.length.toLocaleString()} bytes) as ${STAMP} + sw.js, manifest.json, 3 icons.`);
console.log(`regenerated engine-node/{engine_core.js, store_core.js, rule_g2p_v1.js} from tome-src.`);
console.log(`cmu_skel.json, subtlex_rank.txt, google10k.txt live permanently at the repo root — not part of this build, not touched by it.`);
