/* OCCVM 2.27 — the pigment palettes (OCCVM-L6). One implementation, shared by every conforming tool.
 *
 * GENERATED by occvm/tools/derive-pigments.js. Do not hand-edit: run the generator and commit its output.
 * Authored in occvm/SPINE.md; spliced into a tool by occvm/tools/splice-spine.js. Do not hand-edit the
 * spliced copy either — the next splice reverts it silently.
 *
 * This replaces occvm/minerals.js, which was crystal-era vocabulary that outlived aragonite. The closed
 * three-mineral set existed because under a crystal a colour had to be a mineral that exists with that
 * colour. A dye is not discovered, it is chosen: a lamp manufacturer picks what they want and the wax
 * does not constrain it, so the constraint that produced the closed set died with the crystal.
 *
 * THE EASEMENT, RECORDED RATHER THAN SLID IN. Some handles below are invented where no real pigment
 * fits. Every other name in this system was chosen to be defensible — Fraunces replaced Cinzel because
 * the incised-stone justification died; minerals.js was renamed because the category stopped meaning
 * anything. This is not that. The decorative layer does not answer to the derivation standard the rest
 * of the system does, and saying so here is cheaper than a later reader mistaking it for the naming
 * discipline quietly eroding. Naming a dye after a compound it does not contain would be the dressed-up
 * version; naming it plainly is the honest one.
 *
 * WHAT A PALETTE MAY NOT CHANGE. Semantics are fixed to HUE, never to a slot: green is positive, red is
 * negative, gilt is authority, verdigris-adjacent is active — in every palette, always. A palette is not
 * a remapping of meaning, it is a choice of WHICH green and WHICH red. Nothing a palette does can make
 * confirmed and failed read alike. Measured rather than promised: the smallest positive/negative
 * separation across the five is CIEDE2000 62.3, against the shipped build's own 73.1.
 *
 * WHAT IS AUTHORED AND WHAT IS NOT. Six values per palette are AUTHORED — the four fixed roles and the
 * decorative accent and highlight. No hex among them is derived from a spectrum, a compound or a
 * measurement, and they are labelled authored because a table of colours that looked derived would be
 * the dishonest version. Seven per palette are DERIVED: each is its parent's hex moved by the offset
 * (dL, chroma ratio, dh in CIE L*C*h) that the SHIPPED build already puts between that same pair. The
 * generator's header carries the argument for why those two classes are drawn where they are.
 *
 * OBSIDIAN IS THE ANCHOR AND SELECTING IT IS A NO-OP — measured, not claimed. Its six authored values
 * are this tool's current literals, and the derivation applied to them reproduces the other seven
 * BYTE-IDENTICALLY. Both suites assert that; a change to the derivation that moved today's build would
 * fail before it shipped.
 *
 * ONE MEASURED NEGATIVE, RECORDED RATHER THAN TUNED AWAY. PIGMENT-PALETTES pins `active` to
 * verdigris-adjacent, and three palettes author it 4-16 degrees off that hue, closest to `positive` in
 * `sunset` (1 degree, separated by lightness alone). The shipped build's own positive/active separation
 * is CIEDE2000 14.8; `sunset` reads 11.7 and is the only palette below it. Rotating its `active` onto
 * the verdigris hue was tried and reaches 13.6 — still short, because the limit is its low-chroma green
 * `positive`, not the hue of its `active`. Clearing the floor would mean re-authoring a role hex by eye,
 * which is what this system refuses everywhere else, so the value ships as the plan authors it and the
 * number is on the record. The separation table is asserted per palette, so any change to it must be
 * re-recorded rather than absorbed.
 */
var OCCVM_PIGMENTS = {
  astro: {
    label: "the original — the 1963 Astro, red-orange wax in clear liquid",
    handles: { positive: "Verdigris Bloom", negative: "Ember", gilt: "Filament", active: "Patina", m: "Lava", hi: "Molten" },
    /* authored */
    positive: "#3fbf7e", negative: "#e0475f", gilt: "#ffe9a3", active: "#3f9a86", m: "#ff6b35", hi: "#f7931e",
    /* derived from the authored parent by the shipped build's own L*C*h offset */
    positiveLo: "#1c6a45", negativeLo: "#6b1a2e", giltB: "#d9a52c", giltC: "#7a5510", activeLo: "#23574c", mlo: "#9e3c17", lo: "#b8461d",
  },
  deepwater: {
    label: "blue on clear — the cool counterpart, high contrast against the vessel",
    handles: { positive: "Sea Glass", negative: "Coral Signal", gilt: "Brass Cap", active: "Shallow", m: "Cobalt Drift", hi: "Ice Column" },
    /* authored */
    positive: "#4ecdc4", negative: "#e0475f", gilt: "#ffd97d", active: "#45938a", m: "#2e6fd9", hi: "#8fc9ff",
    /* derived from the authored parent by the shipped build's own L*C*h offset */
    positiveLo: "#2d7873", negativeLo: "#6b1a2e", giltB: "#d89300", giltC: "#744700", activeLo: "#25514d", mlo: "#003677", lo: "#004492",
  },
  acid: {
    label: "green on purple — unmistakably synthetic, unmistakably of its era",
    handles: { positive: "Acid Bloom", negative: "Wine Fault", gilt: "Ultraviolet Gilt", active: "Reactor", m: "Blacklight", hi: "Ooze" },
    /* authored */
    positive: "#7fff4f", negative: "#d6336c", gilt: "#ffe66d", active: "#5cb85c", m: "#9d4edd", hi: "#b6ff3f",
    /* derived from the authored parent by the shipped build's own L*C*h offset */
    positiveLo: "#55a33d", negativeLo: "#600b31", giltB: "#d4a200", giltC: "#765200", activeLo: "#3b713c", mlo: "#541e7e", lo: "#662998",
  },
  sunset: {
    label: "yellow into orange — the lamp that reads as lit even when it is not",
    handles: { positive: "Palm Green", negative: "Rust", gilt: "Late Sun", active: "Frond", m: "Marigold", hi: "Peach Glass" },
    /* authored */
    positive: "#52b788", negative: "#c9432f", gilt: "#ffc857", active: "#40916c", m: "#ffb627", hi: "#ffd6a5",
    /* derived from the authored parent by the shipped build's own L*C*h offset */
    positiveLo: "#276449", negativeLo: "#5b1011", giltB: "#d28400", giltC: "#6b3b00", activeLo: "#204f3a", mlo: "#aa7918", lo: "#c18816",
  },
  obsidian: {
    label: "the current build, preserved — selecting it is a no-op, and that is measured",
    handles: { positive: "Malachite", negative: "Ruby", gilt: "Gilt", active: "Verdigris", m: "Amethyst", hi: "Amethyst Light" },
    /* authored */
    positive: "#3fbf7e", negative: "#e0475f", gilt: "#ffe9a3", active: "#3f9a86", m: "#8d5cf0", hi: "#c9a6ff",
    /* derived from the authored parent by the shipped build's own L*C*h offset */
    positiveLo: "#1c6a45", negativeLo: "#6b1a2e", giltB: "#d9a52c", giltC: "#7a5510", activeLo: "#23574c", mlo: "#4a2a8c", lo: "#5a36a8",
  },
};

/* The default is the current build, so a reader who never opens the picker sees no change at all. */
var OCCVM_PIGMENT_DEFAULT = "obsidian";

/* The token each slot writes, in ONE place, so both tools write the same names to the same properties.
   Before this the two tools each carried their own applyMineral() writing four properties by hand, which
   is how a shared set acquires a local exception. */
var OCCVM_PIGMENT_TOKENS = {
  positive: "--malachite", positiveLo: "--malachite-lo",
  negative: "--ruby", negativeLo: "--ruby-lo",
  gilt: "--gilt-a", giltB: "--gilt-b", giltC: "--gilt-c",
  active: "--verdigris", activeLo: "--verdigris-lo",
  m: "--pigment", mlo: "--pigment-lo",
  hi: "--vein-hi", lo: "--vein-lo",
};

/* The offsets the derivation used, kept beside their output so the table can be checked without running
   the generator, and so a reader can see that the derived column is one rule rather than twenty choices. */
var OCCVM_PIGMENT_OFFSETS = {
  positiveLo: { of: "positive", dL: -29.7893, cr: 0.651910, dh: 1.2592 },
  negativeLo: { of: "negative", dL: -29.2732, cr: 0.592598, dh: -6.0817 },
  giltB: { of: "gilt", dL: -21.8910, cr: 1.780634, dh: -10.8977 },
  giltC: { of: "gilt", dL: -53.6322, cr: 1.180793, dh: -15.6932 },
  activeLo: { of: "active", dL: -24.5906, cr: 0.635887, dh: 1.0520 },
  mlo: { of: "m", dL: -24.6417, cr: 0.731758, dh: 0.3303 },
  lo: { of: "m", dL: -18.1717, cr: 0.823890, dh: -0.0124 },
};

/* Measured separation between the roles a reader must never confuse (CIEDE2000). Recorded, not computed
   at runtime: a number in the source that the suite checks is a number somebody has to re-record when it
   moves, which is the whole point. The shipped build's own posActive is 14.8 and is the floor. */
var OCCVM_PIGMENT_SEPARATION = {
  astro: { posNeg: 73.1, posActive: 14.8 },
  deepwater: { posNeg: 64.4, posActive: 16.6 },
  acid: { posNeg: 89.0, posActive: 18.1 },
  sunset: { posNeg: 62.3, posActive: 11.7 },
  obsidian: { posNeg: 73.1, posActive: 14.8 },
};

/* Writing a palette is one call in both tools. Returns the palette so a caller can read a slot it does
   not write to a token — the canvas does exactly that. */
function occvmApplyPigment(name, style) {
  var p = OCCVM_PIGMENTS[name] || OCCVM_PIGMENTS[OCCVM_PIGMENT_DEFAULT];
  for (var slot in OCCVM_PIGMENT_TOKENS) style.setProperty(OCCVM_PIGMENT_TOKENS[slot], p[slot]);
  return p;
}

if (typeof module !== "undefined") module.exports = {
  PIGMENTS: OCCVM_PIGMENTS, TOKENS: OCCVM_PIGMENT_TOKENS, DEFAULT: OCCVM_PIGMENT_DEFAULT,
  OFFSETS: OCCVM_PIGMENT_OFFSETS, SEPARATION: OCCVM_PIGMENT_SEPARATION, apply: occvmApplyPigment,
};
